### ISSUE TITLE
MSP-EXP430FR4133 Launchpad not working 

### ISSUE THREAD

**Issue by voyo** [spirilis/msprf24#21]
MSP430FR4133 use SPI on eUSCI_A0 (pins 1.0 to 1.3 ) or eUSCI_B0 (pins 5.0 to 5.3)
MSP-EXP430FR4133 Launchpad doesn't have easily exposed P1.0 (LED) and P1.2 (SW1) - thus eUSCI_A0 is actually unusable here.

msprf24 lib needs change to setup for this device eUSCI_B0 with P5 ports (described on Launchpad as SPI pins)

This init function works OK for me. However I'm not sure how would you like to choose proper "#ifdef" 
for this device/MCU , since for 'raw' 4133 eUSCI_A0 is normally available, and it should up to user which eUSCI will be using.
I don't know if there is a good way to detect Launchpad device itself ? Maybe best to use variable in nrf_userconfig.h ?

void spi_init()
{
/\* Configure ports on MSP430 device for USCI_B0 _/
    P5SEL0  |= (BIT1 | BIT2 | BIT3);
/_ USCI_B specific SPI setup */
    UCB0CTLW0 |= UCSWRST;
    UCB0CTLW0 = UCCKPH | UCMST | UCMSB | UCSYNC | UCSSEL_2 | UCSWRST;
    UCB0BRW = 0x01;
    UCB0CTLW0 &= ~UCSWRST;
}

**Comment by spirilis** [comment]
Hi @voyo - Can you test the new update.  I don't have an FR4133 handy, but I added the necessary support for eUSCI_A0 and eUSCI_B0 including spi_transfer9() support for bitbanging the 9th bit.
