### ISSUE TITLE
msp430f2452 examples not run

### ISSUE THREAD

**Issue by Rogil** [spirilis/msprf24#23]
Good day,
A few years ago I used the first version of the nrf24l01 + library in msp430G2452 without problems, but now with the new one it does not work, I have tried it with the G2231 and with the G2553 and it works very well, my IDE is the IAR. You could tell me if you tried it. Thank you.

ANDRÉS FELIPE RODRÍGUEZ

**Comment by spirilis** [comment]
I do not use IAR and have no intention of supporting it.  Please use MSP430-GCC or the TI compiler.
