### ISSUE TITLE
Can't find Interrupt Vector USCI_A0_VECTOR with MSP430-GCC

### ISSUE THREAD

**Issue by deanchester** [spirilis/msprf24#3]
I'm trying to compile this code with MSP430-GCC, although it can't find the interrupt vector USCI_A0_VECTOR. I also can't get code to compile with interrupt vectors like you've supplied I have to use this syntax: 

```
void USCI_RX(void) __attribute__((interrupt(USCIAB0RX_VECTOR)));
```

If that makes a difference at all. What suggestions do you have to work around this? I am trying to compile the transmit and receive examples for the MSP430G2553.

**Comment by dbalatero** [comment]
@deanchester how did you fix this?
